name: Gridsome build & deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.16
      uses: actions/setup-node@v1
      with:
        node-version: '12.16'
    - run: yarn install
    - run: yarn build

    - name: Display-Output-Files
      run: ls dist

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: dist/
        REMOTE_DIR: ${{ secrets.FTP_REMOTE_ROOT }}
        ARGS: --delete --parallel=20
